## This is a basic workflow to help you get started with Actions

#name: CI

## Controls when the workflow will run
#on:
#  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ main, edition_v1 ]
#  pull_request:
#    branches: [ "main" ]

#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

## A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
#  # This workflow contains a single job called "build"
#  build:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#    outputs:
#      branch: ${{ steps.extract_branch.outputs.branch }}
#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3
#      - name: Extract branch name
#        shell: bash
#        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
#        id: extract_branch

#  deploy-main:
#    needs: build
#    runs-on: ubuntu-latest
#    if: ${{ needs.build.outputs.branch == 'main' }}
#    steps:
#      - name: Download built frontend files
#        run: |
#          echo "Build main branch"
#  
#  deploy-edition_v1:
#    needs: build
#    runs-on: ubuntu-latest
#    if: ${{ needs.build.outputs.branch == 'edition_v1' }}
#    steps:
#      - name: Download built frontend files
#        run: |
#          echo "Build edition_v1 branch"


      # Runs a single command using the runners shell
#      - name: Run a one-line script
#        run: echo Hello, world!
#
#      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
