## This is a basic workflow to help you get started with Actions

name: CI

## Controls when the workflow will run
on:
#  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.vars.outputs.tag }}

    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
  deploy-colorado:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.outputs.output1 == 'colorado-v1.0.21' }}
    steps:
      - name: Download built frontend files
        run: |
          echo "Build colorado tag"

  deploy-califor:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.outputs.output1 == 'califor' }}
    steps:
      - name: Download built frontend files
        run: |
          echo "Build california tag"