## This is a basic workflow to help you get started with Actions

name: CI

## Controls when the workflow will run
on:
#  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.vars.outputs.tag }}
      output2: ${{ steps.check-tag.outputs.match }}
      output3: ${{ steps.check-tag1.outputs.match }}

    steps:
      - uses: actions/checkout@v2
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/colorado-v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo ::set-output name=match::true
          fi

      - name: Check Tag1
        id: check-tag1 
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/califor-v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo ::set-output name=match::true
          fi   

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
  deploy-colorado:
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.outputs.output2 == 'true'
#    if:  ${{ needs.build.outputs.output1 == 'colorado-v*' }}
    steps:
      - name: Download built frontend files
        run: |
          echo "Build colorado tag"

  deploy-califor:
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.outputs.output3 == 'true'
#    if: ${{ needs.build.outputs.output1 == 'califor' }}
    steps:
      - name: Download built frontend files
        run: |
          echo "Build california tag"